### ISSUE TITLE
App should check for backend server status

### ISSUE THREAD

**Issue by growupanand** [growupanand/crm-webapp#115]
When an app renders properly, it should use an API request to verify the status of the backend server. If the server is down, an alert or indication should appear on the frontend user interface (UI) to inform the user that the app won't function until the backend server is up.

**Comment by sameer1612** [comment]
@growupanand 

What solution is proposed here? 
1. polling every 10secs. (Less dev time, easy to maintain)
2. setting up a web socket health check endpoint which send heartbeat every 10secs and if heartbeat misses on frontend, it shows message. (More infrastructure time, makes sense if application has a live notification system in place)

**Comment by growupanand** [comment]
@sameer1612 

Here is what I have in mind as a possible solution.

- A single endpoint like "health/internal/" will be required to obtain the status of all services.
- This endpoint will be called once when our front-end app renders to get the status and, if something isn't working, we may display it appropriately in the UI.
- We can also use an express js middleware to perform some health checks; I believe we can define a time period here to prevent it from checking every endpoint.


**Additionally**, your web socket method seems preferable to me, though I haven't tried web socket myself, so you're welcome to use whatever works best for you.

**Comment by sameer1612** [comment]
Lets build it black box way then:

- [ ] Create a endpoint that return key value boolean response for overall system health.
- [ ] For now return express health status. (if result is anything other than 200 ok, FE knows that express is down)
- [ ] Later add implementation for health endpoint to consider other services it's consuming. FE doesn't care how many new services it's monitoring internally. It just renders a hashmap as a table with status.
- [ ] When websocket based notification comes up in this application in future, move api from rest to web socket. [Not part of this ticket]

We're good with this plan? @growupanand

**Comment by growupanand** [comment]
@sameer1612 

looks perfect to me

**Comment by sameer1612** [comment]
good then, assign it to me, I'll raise PR by eod

**Comment by sameer1612** [comment]
@growupanand  I am gonna work on this today but I see no setup docs, sample local env files or database dump of any kind.  
Please detail them out in contribution or readme file otherwise it will quite bad an onboarding experience for anyone. Thanks!

**Comment by growupanand** [comment]
@sameer1612  I've just added `.env.example` files to both the frontend and backend folders in the repo. Give them a try for setting up your local environment. If you encounter any issues, feel free to reach out. I'll also update the README to include setup instructions.
Thanks for your feedback!

**Comment by sameer1612** [comment]
@growupanand Do you have any database dump? Maybe do upload a base zip in `dev-assets` directory.

**Comment by growupanand** [comment]
> @growupanand Do you have any database dump? Maybe do upload a base zip in `dev-assets` directory.

@sameer1612 Currently, I don't have a database dump in the repo. I don't believe we currently require one, but if you have insights or suggestions on this matter, could you please create a detailed issue for it? I'll make sure to look into it as well.

**Comment by growupanand** [comment]
Hey @sameer1612  , I just wanted to make sure you were still on it.
