### ISSUE TITLE
Issue: Invalid verification email

### ISSUE THREAD

**Issue by vatsalsinghkv** [growupanand/crm-webapp#145]
Verification email has localhost as its url
I'd love to fix this issue:

<img width="1440" alt="Screenshot 2023-10-02 at 3 54 33 PM" src="https://github.com/growupanand/crm-webapp/assets/68834718/e1be09d2-ba0a-45c7-8d24-380b3143af77">

**Comment by growupanand** [comment]
Hi @vatsalsinghkv,

Sure i have assigned it to you, thanks for the notice

**Comment by growupanand** [comment]
Hey @vatsalsinghkv  , I just wanted to make sure you were still on it.
